name: Build Android APK & Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev ninja-build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-${{ runner.os }}-stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Configure Flutter
        run: |
          flutter config --no-enable-linux-desktop
          flutter config --enable-android

      - name: Decode Keystore Secret
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build APK
        run: |
          flet build apk \
            --verbose \
            --flutter-build-args="--verbose" \
            --android-signing-key-store android/app/upload-keystore.jks \
            --android-signing-key-store-password "${{ secrets.KEYSTORE_PASSWORD }}" \
            --android-signing-key-alias "${{ secrets.KEY_ALIAS }}" \
            --android-signing-key-password "${{ secrets.KEY_PASSWORD }}"
          
          mv build/apk/*.apk "build/apk/Conversor_Eronsfire.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/apk/Conversor_Eronsfire.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}